# Generated by Django 2.1.7 on 2019-03-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20190322_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='members',
            field=models.SmallIntegerField(default=1, verbose_name='Members'),
        ),
    ]
