# Generated by Django 2.1.7 on 2019-03-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_review_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='residences',
            field=models.IntegerField(default=0),
        ),
    ]
