# Generated by Django 2.1.7 on 2019-03-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotel_residences'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='nights',
            field=models.IntegerField(default=0),
        ),
    ]
