# Generated by Django 2.1.7 on 2019-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotel_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='avg_members_per_stay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='avg_nights_per_stay',
            field=models.FloatField(default=0.0),
        ),
    ]
