# Generated by Django 2.1.7 on 2019-03-23 18:03

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_hotel_data_plot_membergroup_x_avgrating'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='hotel',
        #     name='data_plot_membergroup_x_avgrating',
        #     field=picklefield.fields.PickledObjectField(default=None, editable=False, null=True),
        # ),
    ]
