# Generated by Django 2.1.7 on 2019-03-23 18:05

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20190323_1804'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='hotel',
        #     name='data_plot_membergroup_x_avgrating',
        #     field=picklefield.fields.PickledObjectField(default={}, editable=False),
        # ),
    ]
