# Generated by Django 2.1.7 on 2019-03-23 18:08

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20190323_1807'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='hotel',
        #     name='data_plot_membergroup_x_avgrating',
        # ),
        migrations.AddField(
            model_name='hotel',
            name='data_membergroup_x_avgrating',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
