# Generated by Django 2.1.7 on 2019-03-23 18:10

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20190323_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='data_membergroup_x_avgrating',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
