# Generated by Django 2.1.7 on 2019-03-23 18:12

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_auto_20190323_1810'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='hotel',
        #     name='data_membergroup_x_avgrating',
        # ),
        migrations.AddField(
            model_name='hotel',
            name='data_1',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
