# Generated by Django 2.1.7 on 2019-03-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20190323_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='data_membergroup_x_avgrating',
        ),
    ]
