# Generated by Django 2.1.7 on 2019-04-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_hotel_rating_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Message Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
        ),
    ]
