# Generated by Django 2.1.7 on 2019-04-16 19:35

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_hotel_word_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='word_ocr_groups',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
