# Generated by Django 2.1.7 on 2019-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_hotel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Your name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
            ],
        ),
    ]
